// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMT0ipm-CQu9FwY-U8HfOyScJ4PKo-QA',
    appId: '1:479102879940:web:e1b10246238a3983fb6191',
    messagingSenderId: '479102879940',
    projectId: 'verse37-pmate',
    authDomain: 'verse37-pmate.firebaseapp.com',
    storageBucket: 'verse37-pmate.firebasestorage.app',
    measurementId: 'G-BQZXG41YBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCteujYydXMgghy3NfZCNH6wav5HuPooJA',
    appId: '1:479102879940:android:8b658c0d6d5ee225fb6191',
    messagingSenderId: '479102879940',
    projectId: 'verse37-pmate',
    storageBucket: 'verse37-pmate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABzQfjkTT2d8NV6uJPAAm42V_Nihf2ntc',
    appId: '1:479102879940:ios:23eb9ea1b42edbcdfb6191',
    messagingSenderId: '479102879940',
    projectId: 'verse37-pmate',
    storageBucket: 'verse37-pmate.firebasestorage.app',
    iosBundleId: 'com.verse37.pmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABzQfjkTT2d8NV6uJPAAm42V_Nihf2ntc',
    appId: '1:479102879940:ios:23eb9ea1b42edbcdfb6191',
    messagingSenderId: '479102879940',
    projectId: 'verse37-pmate',
    storageBucket: 'verse37-pmate.firebasestorage.app',
    iosBundleId: 'com.verse37.pmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoMT0ipm-CQu9FwY-U8HfOyScJ4PKo-QA',
    appId: '1:479102879940:web:ed7869b671dfc6defb6191',
    messagingSenderId: '479102879940',
    projectId: 'verse37-pmate',
    authDomain: 'verse37-pmate.firebaseapp.com',
    storageBucket: 'verse37-pmate.firebasestorage.app',
    measurementId: 'G-ZCM6TYCL82',
  );
}
